<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lex.Domain\Lex.Domain.csproj" />
      <ProjectReference Include="..\Lex.Infrastructure\Lex.Infrastructure.csproj" />
    </ItemGroup>

</Project>
